const fs = require('fs');

const lines = [
  "import { getResources } from '../lib/notion';",
  "",
  "export const dynamic = 'force-dynamic';",
  "",
  "export default async function Home() {",
  "  const resources = await getResources();",
  "",
  "  return (",
  "    <div className=\"max-w-6xl mx-auto px-6 py-16\">",
  "      <h1 className=\"text-5xl font-bold mb-3 tracking-tight\">Resources</h1>",
  "      <p className=\"text-gray-400 text-lg mb-12\">A curated list of tools, articles and guides.</p>",
  "      <div className=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5\">",
  "        {resources.map((resource) => (",
  "          <a",
  "            key={resource.id}",
  "            href={resource.url}",
  "            target=\"_blank\"",
  "            rel=\"noopener noreferrer\"",
  "            className=\"group flex flex-col border border-gray-200 rounded-2xl p-6 hover:border-gray-400 hover:shadow-lg transition-all duration-200\"",
  "          >",
  "            <span className=\"text-xs font-semibold text-blue-500 uppercase tracking-widest mb-3\">",
  "              {resource.category}",
  "            </span>",
  "            <h2 className=\"text-base font-semibold text-gray-900 mb-2 group-hover:text-blue-600 transition-colors\">",
  "              {resource.title}",
  "            </h2>",
  "            <p className=\"text-gray-400 text-sm leading-relaxed flex-1\">",
  "              {resource.description}",
  "            </p>",
  "            <span className=\"mt-4 text-xs text-gray-300 group-hover:text-blue-400 transition-colors\">",
  "              Read more →",
  "            </span>",
  "          </a>",
  "        ))}",
  "      </div>",
  "    </div>",
  "  );",
  "}"
];

fs.writeFileSync('app/page.jsx', lines.join('\n'));
console.log('Done!');