const fs = require('fs');

const lines = [
  "'use client';",
  "",
  "import { useState } from 'react';",
  "",
  "export default function ResourcesClient({ resources }) {",
  "  const [active, setActive] = useState('All');",
  "  const categories = ['All', ...new Set(resources.map((r) => r.category).filter(Boolean))];",
  "  const filtered = active === 'All' ? resources : resources.filter((r) => r.category === active);",
  "",
  "  return (",
  "    <div>",
  "      <div className=\"flex gap-2 flex-wrap mb-10\">",
  "        {categories.map((cat) => (",
  "          <button",
  "            key={cat}",
  "            onClick={() => setActive(cat)}",
  "            className={`px-4 py-1.5 rounded-full text-sm font-medium border transition-all duration-150 ${",
  "              active === cat",
  "                ? 'bg-gray-900 text-white border-gray-900'",
  "                : 'bg-white text-gray-500 border-gray-200 hover:border-gray-400'",
  "            }`}",
  "          >",
  "            {cat}",
  "          </button>",
  "        ))}",
  "      </div>",
  "",
  "      <div className=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5\">",
  "        {filtered.map((resource) => (",
  "          <a",
  "            key={resource.id}",
  "            href={resource.url}",
  "            target=\"_blank\"",
  "            rel=\"noopener noreferrer\"",
  "            className=\"group flex flex-col border border-gray-200 rounded-2xl p-6 hover:border-gray-400 hover:shadow-lg transition-all duration-200\"",
  "          >",
  "            <span className=\"text-xs font-semibold text-blue-500 uppercase tracking-widest mb-3\">",
  "              {resource.category}",
  "            </span>",
  "            <h2 className=\"text-base font-semibold text-gray-900 mb-2 group-hover:text-blue-600 transition-colors\">",
  "              {resource.title}",
  "            </h2>",
  "            <p className=\"text-gray-400 text-sm leading-relaxed flex-1\">",
  "              {resource.description}",
  "            </p>",
  "            <span className=\"mt-4 text-xs text-gray-300 group-hover:text-blue-400 transition-colors\">",
  "              Read more \u2192",
  "            </span>",
  "          </a>",
  "        ))}",
  "      </div>",
  "    </div>",
  "  );",
  "}"
];

fs.writeFileSync('app/resources-client.jsx', lines.join('\n'));
console.log('Done!');